//
//  ThaiWord+HouseholdItems.swift
//  ThaiFlashCards
//
//  Created by Dylan Elliott on 11/9/2023.
//

import Foundation

extension ThaiWord {
    static var houseHoldItems: [ThaiWord] {
        [
            ("blender", "เครื่องปั่น"),
            ("bottle opener", "ที่เปิดขวด"),
            ("bowl", "ชาม"),
            ("butcher knife", "มีดแล่เนื้อ"),
            ("can opener", "ที่เปิดกระป๋อง"),
            ("coffee maker", "เครื่องชงกาแฟ"),
            ("counter", "เคาน์เตอร์"),
            ("cup", "ถ้วย"),
            ("cupboard", "ตู้"),
            ("cutting board", "เขียง"),
            ("dishrack", "ที่คว่ำจาน"),
            ("dishwasher", "เครื่องล้างจาน"),
            ("drawer", "ลิ้นชัก"),
            ("foil", "กระดาษฟอยล์"),
            ("fork", "ส้อม"),
            ("freezer", "ตู้แช่"),
            ("kettle", "กาต้มน้ำ"),
            ("knife", "มีด"),
            ("measuring cup", "ถ้วยตวง"),
            ("measuring spoons", "ช้อนตวง"),
            ("microwave", "ไมโครเวฟ"),
            ("mug", "แก้ว"),
            ("oven mitts", "ถุงมือเตาอบ"),
            ("pan", "กะทะ"),
            ("peeler", "เครื่องปอก"),
            ("plate", "จาน"),
            ("pot", "หม้อ"),
            ("refrigerator", "ตู้เย็น"),
            ("rice cooker", "หม้อหุงข้าว"),
            ("sieve", "ตะแกรง"),
            ("Sink", "ซิงค์"),
            ("spatula", "ตะหลิว"),
            ("spoon", "ช้อน"),
            ("bed", "เตียง"),
            ("bedside table", "โต๊ะข้างเตียง"),
            ("blanket", "ผ้าห่ม"),
            ("closet/wardrobe", "ตู้เสื้อผ้า"),
            ("curtains", "ผ้าม่าน"),
            ("hangers", "ไม้แขวนเสื้อ"),
            ("pillow", "หมอน"),
            ("sheets", "ปลอกหมอน"),
            ("shelf", "ชั้นวาง"),
            ("bathtub", "อ่างอาบน้ำ"),
            ("hot water heater", "เครื่องทำน้ำอุ่น"),
            ("jacuzzi", "จากุซซี่"),
            ("mirror", "กระจก"),
            ("shampoo", "แชมพู"),
            ("shower cap", "หมวกอาบน้ำ"),
            ("shower curtain", "ม่านอาบน้ำ"),
            ("shower head", "ฝักบัวอาบน้ำ"),
            ("soap", "สบู่"),
            ("tiles", "กระเบื้อง"),
            ("toilet", "สุขา"),
            ("toilet paper", "กระดาษชำระ"),
            ("toilet seat", "ที่รองชักโครก"),
            ("toothbrush", "แปรงสีฟัน"),
            ("toothpaste", "ยาสีฟัน"),
            ("towel", "ผ้าขนหนู"),
            ("bookshelf", "ชั้นวางหนังสือ"),
            ("built-in shelf", "ชั้นวางของในตัว"),
            ("cabinet", "ตู้"),
            ("carpet", "พรม"),
            ("chair", "เก้าอี้"),
            ("dining table", "โต๊ะอาหาร"),
            ("lamp", "โคมไฟ"),
            ("picture frame", "กรอบรูป"),
            ("sofa/couch", "โซฟา"),
            ("table", "โต๊ะ"),
            ("television/TV", "ทีวี"),
            ("hammock", "เปลญวน"),
            ("hose", "สายยาง"),
            ("lawn mower", "เครื่องตัดหญ้า"),
            ("shears", "กรรไกรสวน"),
            ("adaptor", "อะแดปเตอร์"),
            ("air conditioner", "เครื่องปรับอากาศ"),
            ("door", "ประตู"),
            ("dryer", "เครื่องเป่า"),
            ("extension cord", "สายไฟต่อ"),
            ("fan", "พัดลม"),
            ("floor mat", "พรมปูพื้น"),
            ("garbage bag", "ถุงขยะ"),
            ("garbage bin", "ถังขยะ"),
            ("measuring tape", "ตลับเมตร"),
            ("printer", "เครื่องพิมพ์"),
            ("shoe cupboard", "ตู้รองเท้า"),
            ("storage container", "ตู้เก็บของ"),
            ("vase", "แจกัน"),
            ("washing machine", "เครื่องซักผ้า"),
            ("window", "หน้าต่าง"),
            ("vacuum", "เครื่องดูดฝุ่น")
        ]
        .map { .init(script: $0.1, meaning: $0.0.lowercased()) }
    }
}
